apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spig-starter-kit.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "spig-starter-kit.name" . }}
    helm.sh/chart: {{ include "spig-starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spig-starter-kit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spig-starter-kit.name" . }}
        #version: 1.0-snapshot
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- if .Values.istio }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        sidecar.istio.io/inject: "true"
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spig-starter-kit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.filebeat.enabled }}
       - name: log-sidecar
         env:
           - name: IMAGE_NAME
             value: hello-world
           - name: ENV
             value: LOCAL
           - name: ELASTIC_HOSTS
             value: http://34.66.241.173:9200
         image: docker.elastic.co/beats/filebeat:7.4.2
         imagePullPolicy: Always
         volumeMounts:
           - name: shared-data
             mountPath: /var/logs/microservice
           - name: filebeat-config
             mountPath: /usr/share/filebeat/filebeat.yml
             subPath: filebeat.yml              
        {{- end }}
        #- name: hello-world
        - name: {{ .Chart.Name }}
          #image: image-registry.openshift-image-registry.svc:5000/project01-dev/hello-world:1.0-snapshot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          #imagePullPolicy: Always
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAEGER_PROPAGATION
              value: b3
            - name: JAEGER_TRACEID_128BIT
              value: "true"
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.istio-system:14268/api/traces
            - name: SECRET_DATA_1
              valueFrom:
                secretKeyRef:
                  name: hello-world-secret
                  key: SECRET_DATA_1
            - name: SECRET_DATA_2
              valueFrom:
                secretKeyRef:
                  name: hello-world-secret
                  key: SECRET_DATA_2
          volumeMounts:
            - name: shared-data
              mountPath: /var/logs/microservice
            - name: logging-config
              mountPath: /logback-spring.xml
              subPath: logback-spring.xml
            - name: application-config
              mountPath: /application.yml
              subPath: application.yml
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 15
      volumes:
        - name: application-config
          configMap:
            name: hello-world-config
        - name: logging-config
          configMap:
            name: hello-world-logback-config
        - name: shared-data
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-sidecar-config
            items:
              - key: filebeat.yml
                path: filebeat.yml




