apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "spig-starter-kit.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    # In this case, accept all host name
    - "{{ .Release.Namespace }}/*"