{{- if .Values.mtls.enabled -}}
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: require-mtls-jwt
spec:
  origins:
  - jwt:
      issuer: http://34.87.119.98:8080/auth/realms/master
      jwksUri: http://34.87.119.98:8080/auth/realms/master/protocol/openid-connect/certs
      trigger_rules:
      - excluded_paths:
        - exact: /ibm/rest/testing/hello-world/swagger-ui.html
        - prefix: /ibm/rest/testing/hello-world/webjars
        - prefix: /ibm/rest/testing/hello-world/swagger-resources
        - prefix: /ibm/rest/testing/hello-world/v2/api-docs
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
  targets:
  - name: hello-world-svc.project01-dev.svc.cluster.local
{{- end }}